import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
	// `worker-configuration.d.ts` is generated by `wrangler types`; never lint it.
	{ ignores: ["dist", "worker-configuration.d.ts"] },
	{
		extends: [js.configs.recommended, ...tseslint.configs.recommended],
		files: ["**/*.{ts,tsx}"],
		languageOptions: {
			ecmaVersion: 2020,
		},
		plugins: {
			"react-hooks": reactHooks,
			"react-refresh": reactRefresh,
		},
		rules: {
			...reactHooks.configs.recommended.rules,
			"react-refresh/only-export-components": [
				"warn",
				{ allowConstantExport: true },
			],
		},
	},
	// Client (browser) code: React SPA + shared isomorphic modules.
	{
		files: ["src/react-app/**/*.{ts,tsx}", "src/shared/**/*.ts"],
		languageOptions: { globals: globals.browser },
	},
	// Client-bundle boundary: nothing under src/react-app/** may import Drizzle or
	// the Worker's db layer, or it lands in the client bundle. This lint catches the
	// bad import at edit time (including a stripped `import type`, which the
	// post-build bundle scan is blind to) instead of at deploy time.
	{
		files: ["src/react-app/**/*.{ts,tsx}"],
		rules: {
			"@typescript-eslint/no-restricted-imports": [
				"error",
				{
					paths: [
						{
							name: "drizzle-orm",
							message:
								"src/react-app must never import Drizzle or the Worker's db layer - see the client-bundle boundary note in docs/ARCHITECTURE.md.",
						},
					],
					patterns: [
						{
							group: ["**/worker/db/**"],
							message:
								"src/react-app must never import Drizzle or the Worker's db layer - see the client-bundle boundary note in docs/ARCHITECTURE.md.",
						},
					],
				},
			],
		},
	},
	// Worker code runs in the Cloudflare runtime, NOT the browser: use a
	// non-browser global set so browser-only globals (window/document) are flagged.
	{
		files: ["src/worker/**/*.ts"],
		languageOptions: {
			globals: { ...globals.node, ...globals.serviceworker },
		},
		rules: {
			// `declare global { namespace Cloudflare { interface Env {...} } }` is the
			// standard Cloudflare Workers Env-augmentation pattern (worker-configuration.d.ts
			// itself uses this shape) - allow ambient `declare namespace` here without
			// permitting non-ambient namespaces elsewhere.
			"@typescript-eslint/no-namespace": ["error", { allowDeclarations: true }],
		},
	},
	// shadcn/ui primitives co-export a component AND a `*Variants` cva helper from
	// the same file, which trips react-refresh/only-export-components. That is the
	// intended shadcn shape, so relax the rule for that directory only.
	{
		files: ["src/react-app/components/ui/**/*.{ts,tsx}"],
		rules: { "react-refresh/only-export-components": "off" },
	},
);
